/**
 * This class is generated by jOOQ
 */
package com.interview.yoti.robot.dao.jooq.tables;


import com.interview.yoti.robot.dao.jooq.Yoti;
import com.interview.yoti.robot.dao.jooq.tables.records.FlywaySchemaHistoryRecord;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlywaySchemaHistory extends TableImpl<FlywaySchemaHistoryRecord> {

	private static final long serialVersionUID = 1738411341;

	/**
	 * The reference instance of <code>YOTI.flyway_schema_history</code>
	 */
	public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = new FlywaySchemaHistory();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FlywaySchemaHistoryRecord> getRecordType() {
		return FlywaySchemaHistoryRecord.class;
	}

	/**
	 * The column <code>YOTI.flyway_schema_history.installed_rank</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, Integer> INSTALLED_RANK = createField("installed_rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.version</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.description</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.type</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.script</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, String> SCRIPT = createField("script", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.checksum</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, Integer> CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.installed_by</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, String> INSTALLED_BY = createField("installed_by", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.installed_on</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, Timestamp> INSTALLED_ON = createField("installed_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.execution_time</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, Integer> EXECUTION_TIME = createField("execution_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>YOTI.flyway_schema_history.success</code>.
	 */
	public final TableField<FlywaySchemaHistoryRecord, Boolean> SUCCESS = createField("success", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * Create a <code>YOTI.flyway_schema_history</code> table reference
	 */
	public FlywaySchemaHistory() {
		this("flyway_schema_history", null);
	}

	/**
	 * Create an aliased <code>YOTI.flyway_schema_history</code> table reference
	 */
	public FlywaySchemaHistory(String alias) {
		this(alias, FLYWAY_SCHEMA_HISTORY);
	}

	private FlywaySchemaHistory(String alias, Table<FlywaySchemaHistoryRecord> aliased) {
		this(alias, aliased, null);
	}

	private FlywaySchemaHistory(String alias, Table<FlywaySchemaHistoryRecord> aliased, Field<?>[] parameters) {
		super(alias, Yoti.YOTI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FlywaySchemaHistory as(String alias) {
		return new FlywaySchemaHistory(alias, this);
	}

	/**
	 * Rename this table
	 */
	public FlywaySchemaHistory rename(String name) {
		return new FlywaySchemaHistory(name, null);
	}
}
