/**
 * This class is generated by jOOQ
 */
package com.interview.yoti.robot.dao.jooq.tables;


import com.interview.yoti.robot.dao.jooq.Yoti;
import com.interview.yoti.robot.dao.jooq.tables.records.HooverResponseRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HooverResponse extends TableImpl<HooverResponseRecord> {

	private static final long serialVersionUID = -1990403666;

	/**
	 * The reference instance of <code>YOTI.HOOVER_RESPONSE</code>
	 */
	public static final HooverResponse HOOVER_RESPONSE = new HooverResponse();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<HooverResponseRecord> getRecordType() {
		return HooverResponseRecord.class;
	}

	/**
	 * The column <code>YOTI.HOOVER_RESPONSE.REQUEST_TIMESTAMP</code>.
	 */
	public final TableField<HooverResponseRecord, Long> REQUEST_TIMESTAMP = createField("REQUEST_TIMESTAMP", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>YOTI.HOOVER_RESPONSE.POSITION_HOOVER</code>.
	 */
	public final TableField<HooverResponseRecord, String> POSITION_HOOVER = createField("POSITION_HOOVER", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647).nullable(false), this, "");

	/**
	 * The column <code>YOTI.HOOVER_RESPONSE.PATCHES_CLEANED</code>.
	 */
	public final TableField<HooverResponseRecord, Integer> PATCHES_CLEANED = createField("PATCHES_CLEANED", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>YOTI.HOOVER_RESPONSE</code> table reference
	 */
	public HooverResponse() {
		this("HOOVER_RESPONSE", null);
	}

	/**
	 * Create an aliased <code>YOTI.HOOVER_RESPONSE</code> table reference
	 */
	public HooverResponse(String alias) {
		this(alias, HOOVER_RESPONSE);
	}

	private HooverResponse(String alias, Table<HooverResponseRecord> aliased) {
		this(alias, aliased, null);
	}

	private HooverResponse(String alias, Table<HooverResponseRecord> aliased, Field<?>[] parameters) {
		super(alias, Yoti.YOTI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverResponse as(String alias) {
		return new HooverResponse(alias, this);
	}

	/**
	 * Rename this table
	 */
	public HooverResponse rename(String name) {
		return new HooverResponse(name, null);
	}
}
