/**
 * This class is generated by jOOQ
 */
package com.interview.yoti.robot.dao.jooq.tables.records;


import com.interview.yoti.robot.dao.jooq.tables.HooverRequests;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HooverRequestsRecord extends TableRecordImpl<HooverRequestsRecord> implements Record5<Long, String, String, String, String> {

	private static final long serialVersionUID = 582298955;

	/**
	 * Setter for <code>YOTI.HOOVER_REQUESTS.REQUEST_TIMESTAMP</code>.
	 */
	public void setRequestTimestamp(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>YOTI.HOOVER_REQUESTS.REQUEST_TIMESTAMP</code>.
	 */
	public Long getRequestTimestamp() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>YOTI.HOOVER_REQUESTS.DIMENSION_ROOM</code>.
	 */
	public void setDimensionRoom(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>YOTI.HOOVER_REQUESTS.DIMENSION_ROOM</code>.
	 */
	public String getDimensionRoom() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>YOTI.HOOVER_REQUESTS.POSITION_HOOVER</code>.
	 */
	public void setPositionHoover(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>YOTI.HOOVER_REQUESTS.POSITION_HOOVER</code>.
	 */
	public String getPositionHoover() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>YOTI.HOOVER_REQUESTS.DIRT_PATCHES</code>.
	 */
	public void setDirtPatches(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>YOTI.HOOVER_REQUESTS.DIRT_PATCHES</code>.
	 */
	public String getDirtPatches() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>YOTI.HOOVER_REQUESTS.INSTRUCTIONS</code>.
	 */
	public void setInstructions(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>YOTI.HOOVER_REQUESTS.INSTRUCTIONS</code>.
	 */
	public String getInstructions() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, String, String, String, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Long, String, String, String, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return HooverRequests.HOOVER_REQUESTS.REQUEST_TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return HooverRequests.HOOVER_REQUESTS.DIMENSION_ROOM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return HooverRequests.HOOVER_REQUESTS.POSITION_HOOVER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return HooverRequests.HOOVER_REQUESTS.DIRT_PATCHES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return HooverRequests.HOOVER_REQUESTS.INSTRUCTIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getRequestTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getDimensionRoom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPositionHoover();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDirtPatches();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getInstructions();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverRequestsRecord value1(Long value) {
		setRequestTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverRequestsRecord value2(String value) {
		setDimensionRoom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverRequestsRecord value3(String value) {
		setPositionHoover(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverRequestsRecord value4(String value) {
		setDirtPatches(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverRequestsRecord value5(String value) {
		setInstructions(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverRequestsRecord values(Long value1, String value2, String value3, String value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HooverRequestsRecord
	 */
	public HooverRequestsRecord() {
		super(HooverRequests.HOOVER_REQUESTS);
	}

	/**
	 * Create a detached, initialised HooverRequestsRecord
	 */
	public HooverRequestsRecord(Long requestTimestamp, String dimensionRoom, String positionHoover, String dirtPatches, String instructions) {
		super(HooverRequests.HOOVER_REQUESTS);

		setValue(0, requestTimestamp);
		setValue(1, dimensionRoom);
		setValue(2, positionHoover);
		setValue(3, dirtPatches);
		setValue(4, instructions);
	}
}
