/**
 * This class is generated by jOOQ
 */
package com.interview.yoti.robot.dao.jooq;


import com.interview.yoti.robot.dao.jooq.tables.FlywaySchemaHistory;
import com.interview.yoti.robot.dao.jooq.tables.HooverRequests;
import com.interview.yoti.robot.dao.jooq.tables.HooverResponse;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in YOTI
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table YOTI.flyway_schema_history
	 */
	public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.interview.yoti.robot.dao.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

	/**
	 * The table YOTI.HOOVER_REQUESTS
	 */
	public static final HooverRequests HOOVER_REQUESTS = com.interview.yoti.robot.dao.jooq.tables.HooverRequests.HOOVER_REQUESTS;

	/**
	 * The table YOTI.HOOVER_RESPONSE
	 */
	public static final HooverResponse HOOVER_RESPONSE = com.interview.yoti.robot.dao.jooq.tables.HooverResponse.HOOVER_RESPONSE;
}
