/**
 * This class is generated by jOOQ
 */
package com.interview.yoti.robot.dao.jooq;


import com.interview.yoti.robot.dao.jooq.tables.FlywaySchemaHistory;
import com.interview.yoti.robot.dao.jooq.tables.HooverRequests;
import com.interview.yoti.robot.dao.jooq.tables.HooverResponse;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Yoti extends SchemaImpl {

	private static final long serialVersionUID = 322570322;

	/**
	 * The reference instance of <code>YOTI</code>
	 */
	public static final Yoti YOTI = new Yoti();

	/**
	 * No further instances allowed
	 */
	private Yoti() {
		super("YOTI");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
			HooverRequests.HOOVER_REQUESTS,
			HooverResponse.HOOVER_RESPONSE);
	}
}
