/**
 * This class is generated by jOOQ
 */
package com.interview.yoti.robot.dao.jooq.tables.records;


import com.interview.yoti.robot.dao.jooq.tables.HooverResponse;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HooverResponseRecord extends TableRecordImpl<HooverResponseRecord> implements Record3<Long, String, Integer> {

	private static final long serialVersionUID = -1904067698;

	/**
	 * Setter for <code>YOTI.HOOVER_RESPONSE.REQUEST_TIMESTAMP</code>.
	 */
	public void setRequestTimestamp(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>YOTI.HOOVER_RESPONSE.REQUEST_TIMESTAMP</code>.
	 */
	public Long getRequestTimestamp() {
		return (Long) getValue(0);
	}

	/**
	 * Setter for <code>YOTI.HOOVER_RESPONSE.POSITION_HOOVER</code>.
	 */
	public void setPositionHoover(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>YOTI.HOOVER_RESPONSE.POSITION_HOOVER</code>.
	 */
	public String getPositionHoover() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>YOTI.HOOVER_RESPONSE.PATCHES_CLEANED</code>.
	 */
	public void setPatchesCleaned(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>YOTI.HOOVER_RESPONSE.PATCHES_CLEANED</code>.
	 */
	public Integer getPatchesCleaned() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, String, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Long, String, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return HooverResponse.HOOVER_RESPONSE.REQUEST_TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return HooverResponse.HOOVER_RESPONSE.POSITION_HOOVER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return HooverResponse.HOOVER_RESPONSE.PATCHES_CLEANED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getRequestTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getPositionHoover();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getPatchesCleaned();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverResponseRecord value1(Long value) {
		setRequestTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverResponseRecord value2(String value) {
		setPositionHoover(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverResponseRecord value3(Integer value) {
		setPatchesCleaned(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HooverResponseRecord values(Long value1, String value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached HooverResponseRecord
	 */
	public HooverResponseRecord() {
		super(HooverResponse.HOOVER_RESPONSE);
	}

	/**
	 * Create a detached, initialised HooverResponseRecord
	 */
	public HooverResponseRecord(Long requestTimestamp, String positionHoover, Integer patchesCleaned) {
		super(HooverResponse.HOOVER_RESPONSE);

		setValue(0, requestTimestamp);
		setValue(1, positionHoover);
		setValue(2, patchesCleaned);
	}
}
